#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Sets up the snapper group ACL that lets the BackIt Up backup read the
# newest system snapshot and store a copy of it, then verifies the copy can
# actually be read as your user.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()
WRITTEN_SECRET=()
SKIPPED=()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the terminal; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  verifies each step as it lands. Stop any time with Ctrl-C and re-run\n'
  printf '  later; every stage is safe to repeat.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

finish() {
  _clear
  printf '\n%s%s  ✓ Done%s\n' "$BOLD" "$GREEN" "$RESET"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

SNAPPER_CONFIG="/etc/snapper/configs/root"
BACKUP_CONFIG="/etc/snapper/configs/root.bak-backitup"

banner "Snapper ACL: the backup's system snapshot copy"

# ── Stage 1: the current state ────────────────────────────────────────────
stage "Check the machine"
if id -nG | grep -qw wheel; then
  note "you are in the wheel group - the group the ACL will name"
else
  warn "you are not in the wheel group; the ACL below must name a group you are in"
fi
if grep -q '^ALLOW_GROUPS=' "$SNAPPER_CONFIG" 2>/dev/null; then
  note "current: $(grep '^ALLOW_GROUPS=' "$SNAPPER_CONFIG")"
else
  note "ALLOW_GROUPS is not set yet"
fi
if grep -q '^SYNC_ACL=' "$SNAPPER_CONFIG" 2>/dev/null; then
  note "current: $(grep '^SYNC_ACL=' "$SNAPPER_CONFIG")"
else
  note "SYNC_ACL is not set yet (snapper's default is no)"
fi
say ""
say "What this unlocks: the backup reads the newest system snapshot and"
say "stores a copy of it, so the system's installed state survives disk loss."
say "Files inside a snapshot keep their own permissions, so root-only files"
say "(shadow, host keys, /root) stay closed to you and out of the backup."
say ""
say "If your sudo timestamp has expired, run: sudo -v"

# ── Stage 2: back up the config ───────────────────────────────────────────
stage "Back up the snapper config"
if confirm "Copy $SNAPPER_CONFIG to $BACKUP_CONFIG (needs sudo)?"; then
  if sudo cp -- "$SNAPPER_CONFIG" "$BACKUP_CONFIG"; then
    note "backed up"
  else
    warn "the backup copy failed; fix that before continuing"
    SKIPPED+=("the config backup copy")
  fi
else
  note "skipped the backup copy"
fi

# ── Stage 3: the two lines ────────────────────────────────────────────────
stage "Add ALLOW_GROUPS and SYNC_ACL"
say "Two lines let the wheel group list and read snapshots. Snapper applies"
say "the ACL to snapshots created after SYNC_ACL is set; older ones stay"
say "root-only, which does not matter here: every backup creates a new one."
if confirm "Append the two lines to $SNAPPER_CONFIG (needs sudo)?"; then
  grep -q '^ALLOW_GROUPS=' "$SNAPPER_CONFIG" || echo 'ALLOW_GROUPS="wheel"' | sudo tee -a -- "$SNAPPER_CONFIG" >/dev/null
  grep -q '^SYNC_ACL=' "$SNAPPER_CONFIG" || echo 'SYNC_ACL="yes"' | sudo tee -a -- "$SNAPPER_CONFIG" >/dev/null
  note "now in the config:"
  grep -E '^(ALLOW_GROUPS|SYNC_ACL)=' "$SNAPPER_CONFIG" | while IFS= read -r line; do note "    $line"; done
else
  note "skipped; the copy stays skipped until the lines are in"
  SKIPPED+=("ALLOW_GROUPS and SYNC_ACL in $SNAPPER_CONFIG")
fi

# ── Stage 4: create a snapshot ────────────────────────────────────────────
stage "Create a snapshot with the ACL in place"
say "The existing sudoers line makes this passwordless. The snapshot command"
say "prints no path of its own, so this stage also shows what it prints -"
say "the backup finds the newest directory under /.snapshots instead."
warn "Snapper's NUMBER_LIMIT is 5: creating one prunes the oldest snapshot in the pool."
if confirm "Run omarchy-snapshot create?"; then
  if out="$(omarchy-snapshot create 2>&1)"; then
    note "created; the command printed:"
    printf '%s\n' "$out" | while IFS= read -r line; do note "    $line"; done
  else
    rc=$?
    warn "create failed (exit $rc):"
    printf '%s\n' "${out:-}" | while IFS= read -r line; do note "    $line"; done
    SKIPPED+=("omarchy-snapshot create")
  fi
else
  note "skipped; the copy cannot be verified without a snapshot created after the ACL"
  SKIPPED+=("omarchy-snapshot create")
fi

# ── Stage 5: verify as the user ───────────────────────────────────────────
stage "Verify the backup can read it"
newest="$(ls -1t -- /.snapshots 2>/dev/null | head -n 1 || true)"
if [ -z "$newest" ]; then
  warn "/.snapshots is still not listable as you; the ACL did not land."
  say "Check whether the ACE is on the directory:"
  step "sudo getfacl /.snapshots"
  say "Snapper syncs the ACL onto snapshots created after SYNC_ACL was set,"
  say "so create another snapshot and re-run this wizard."
  SKIPPED+=("the ACL did not land on /.snapshots")
else
  snap_path="/.snapshots/$newest/snapshot"
  note "newest snapshot: $newest"
  if [ -d "$snap_path" ] && [ -n "$(find "$snap_path" -mindepth 1 -print -quit 2>/dev/null)" ]; then
    note "the snapshot tree is readable and not empty"
    if [ -r "$snap_path/etc" ]; then
      note "/etc inside it is walkable"
    fi
    if [ -r "$snap_path/etc/shadow" ]; then
      warn "/etc/shadow inside the snapshot is readable - more open than expected"
    else
      note "/etc/shadow stays closed (root:shadow 640): the sensitive files stay out"
    fi
    say ""
    say "The next backup stores a copy of this snapshot. The panel shows the"
    say "verdict, and the backup's audit counts the copy as by-design."
  else
    warn "$snap_path reads as empty - an unmounted snapshot subvolume."
    say "The backup reports 'could not read it' rather than copying air."
    say "Try mounting it and re-run this wizard:"
    step "sudo snapper -c root mount && ls $snap_path"
    SKIPPED+=("the snapshot subvolume reads as empty")
  fi
fi

finish
